language: python
sudo: false
python:
  - "2.7"
services:
  - couchdb
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
install:
  - bin/buildout -N
script:
  - bin/nosetests
after_success:
  - bin/coveralls
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4000c648ae50a8d3fcee
    on_success: true
    on_failure: true
    on_start: false
